[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "3269c8262d363e23ed122fcf5b97f6d44abef91e"
owners = ["Glyceri"]
	changelog = """
    [2.3.0.3]
    Fixes a couple tooltip and colour bugs.
"""
